name: Python app ci/cd
on:
  push:
    branches: ["main"]
jobs:
  run-simulation:
    runs-on: [self-hosted, main_arbor]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: stop existing all container
        run: |
          docker compose down || true
          docker system prune -a 

      - name: building docker compose file
        run: |
          docker compose up -d 

      - name: create .env file
        run: |
          echo "${{secrets.ENV_FILE}}" > .env
